language: ruby

rvm:
  - 1.9.3

bundler_args: --without development

before_install: gem install bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database test;' -U postgres
  - rake db:migrate
